global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: 'fastapi'
    metrics_path: /api/metrics
    static_configs:
      - targets: ["fastapi-1:5000",
                  "fastapi-2:5000",
                  "fastapi-3:5000",
                  "fastapi-4:5000"]

  - job_name: 'node-exporter'
    static_configs:
      - targets: ["node_exporter:9100"]
