entryPoints:
  web:
    address: :80
  fastapi:
    address: :5000

providers:
  file:
    filename: dynamic.yml
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true