version: "3"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/static.yml:/traefik.yml:ro
      - ./traefik/dynamic.yml:/dynamic.yml:ro
    restart: unless-stopped

  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_DB_NAME=${DB_NAME}
    ports:
      - ${DB_PORT_OUT}:${DB_PORT_IN}
    volumes:
      - "${PWD}/mssql/data:/var/opt/mssql/data"
      - "${PWD}/mssql/log:/var/opt/mssql/log"
      - "${PWD}/mssql/scripts:/scripts"
    restart: unless-stopped

  fastapi:
    image: fastapi:latest
    container_name: fastapi
    environment:
      - API_CONFIG_ENVIRONMENT=local
    env_file:
      - ./environments/.env.fastapi
    volumes:
      - ./shared/fastapi:/home/appuser/shared
    depends_on:
      - mssql

  react:
    image: react:latest
    container_name: react_server
    volumes:
      - ./shared/nginx/cache:/usr/src/app/cache
    depends_on:
      - fastapi
