import os

API_CONFIG_MAX_DB_CONNECTION_RETRIES = os.getenv(
    "API_CONFIG_MAX_DB_CONNECTION_RETRIES", 5
)

API_CONFIG_DB_CONNECTION_RETRY_INTERVAL = os.getenv(
    "API_CONFIG_DB_CONNECTION_RETRY_INTERVAL", 5
)  # seconds

API_CONFIG_MSSQL_USERNAME = os.getenv("API_CONFIG_MSSQL_USERNAME", "dseu")

API_CONFIG_MSSQL_PASSWORD = os.getenv("API_CONFIG_MSSQL_PASSWORD", "dseu1234")

API_CONFIG_MSSQL_SERVER_NAME = os.getenv(
    "API_CONFIG_MSSQL_SERVER_NAME", "localhost\\SQLEXPRESS"
)

API_CONFIG_MSSQL_DB_NAME = os.getenv("API_CONFIG_MSSQL_DB_NAME", "etimetracklite")

API_CONFIG_DB_CONNECTION_POOL_SIZE = os.getenv("API_CONFIG_DB_CONNECTION_POOL_SIZE", 20)

API_CONFIG_SERVER_SECRET_KEY = os.getenv(
    "API_CONFIG_SERVER_SECRET_KEY", "h^+xf9b(am!h^v*6jxsl)jdps5v*j1u65ggn%v=-6vof9#35lg"
)

API_CONFIG_HASHING_ALGORITHM = os.getenv("API_CONFIG_HASHING_ALGORITHM", "HS256")

API_CONFIG_ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv(
    "API_CONFIG_ACCESS_TOKEN_EXPIRE_MINUTES", 60
)

API_CONFIG_TEMPLATE_FOLDER_PATH = os.getenv(
    "API_CONFIG_TEMPLATE_FOLDER_PATH", "app/templates"
)
